#!/usr/bin/env python3
"""Build a single-file JavaScript bundle for the admin UI.

Inputs:
  - CLI args selecting index HTML, stylesheet, output path, and embedding mode.
Outputs:
  - Writes one JavaScript bundle file to the requested output path.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class UiBundleParts:
    """Container for extracted admin UI assets.

    Inputs:
      - bootstrap_script: Small theme/bootstrap script from index.html.
      - app_script: Main UI logic script from index.html.
      - body_markup: Static markup from index.html body (script tags removed).
      - styles_css: CSS text from styles.css.
    Outputs:
      - Immutable asset container used by bundle renderers.
    """

    bootstrap_script: str
    app_script: str
    body_markup: str
    styles_css: str


def parse_args() -> argparse.Namespace:
    """Parse command-line options for bundle generation.

    Inputs:
      - Process CLI argv.
    Outputs:
      - argparse.Namespace with resolved option values.
    """

    parser = argparse.ArgumentParser(
        description="Build a single JavaScript admin UI bundle for CDN delivery."
    )
    parser.add_argument(
        "--index",
        default="src/foghorn/html/index.html",
        help="Path to admin index.html (default: src/foghorn/html/index.html).",
    )
    parser.add_argument(
        "--styles",
        default="src/foghorn/html/styles.css",
        help="Path to admin stylesheet (default: src/foghorn/html/styles.css).",
    )
    parser.add_argument(
        "--output",
        default="dist/foghorn-admin-ui.cdn.js",
        help="Output bundle path (default: dist/foghorn-admin-ui.cdn.js).",
    )
    parser.add_argument(
        "--runtime-only",
        action="store_true",
        help=(
            "Emit only the extracted JavaScript runtime from index.html "
            "(no embedded HTML/CSS)."
        ),
    )
    return parser.parse_args()


def _extract_inline_scripts(index_html: str) -> list[str]:
    """Extract inline (non-src) script blocks from index markup.

    Inputs:
      - index_html: Entire index.html source text.
    Outputs:
      - Ordered list of inline script contents.
    """

    scripts: list[str] = []
    for match in re.finditer(
        r"<script\b(?P<attrs>[^>]*)>(?P<content>.*?)</script\s*>",
        index_html,
        flags=re.IGNORECASE | re.DOTALL,
    ):
        attrs = match.group("attrs") or ""
        if re.search(r"\bsrc\s*=", attrs, flags=re.IGNORECASE):
            continue
        scripts.append((match.group("content") or "").strip())
    return scripts


def _extract_body_markup(index_html: str) -> str:
    """Extract HTML body content with script tags removed.

    Inputs:
      - index_html: Entire index.html source text.
    Outputs:
      - Body markup string without inline/external script blocks.
    """

    body_match = re.search(
        r"<body[^>]*>(?P<body>.*)</body>",
        index_html,
        flags=re.IGNORECASE | re.DOTALL,
    )
    if not body_match:
        raise ValueError("Unable to locate <body>...</body> in index.html")
    body_markup = body_match.group("body")
    body_markup = re.sub(
        r"<script\b[^>]*>.*?</script\s*>",
        "",
        body_markup,
        flags=re.IGNORECASE | re.DOTALL,
    )
    return body_markup.strip()


def extract_assets(index_path: Path, styles_path: Path) -> UiBundleParts:
    """Read and split admin UI assets from source files.

    Inputs:
      - index_path: Path to index.html.
      - styles_path: Path to styles.css.
    Outputs:
      - UiBundleParts extracted from source assets.
    """

    index_html = index_path.read_text(encoding="utf-8")
    styles_css = styles_path.read_text(encoding="utf-8")
    inline_scripts = _extract_inline_scripts(index_html)
    if not inline_scripts:
        raise ValueError("No inline script blocks found in index.html")

    bootstrap_script = inline_scripts[0] if len(inline_scripts) > 1 else ""
    app_script = max(inline_scripts, key=len)
    body_markup = _extract_body_markup(index_html)

    return UiBundleParts(
        bootstrap_script=bootstrap_script,
        app_script=app_script,
        body_markup=body_markup,
        styles_css=styles_css,
    )


def render_runtime_only_bundle(parts: UiBundleParts) -> str:
    """Render a JavaScript bundle containing only runtime code.

    Inputs:
      - parts: Extracted UI asset components.
    Outputs:
      - JavaScript bundle source text.
    """

    chunks = [
        "/* Generated by scripts/build_admin_ui_bundle.py (runtime-only). */",
        "/* eslint-disable */",
    ]
    if parts.bootstrap_script:
        chunks.append(parts.bootstrap_script.strip())
    chunks.append(parts.app_script.strip())
    chunks.append("")
    return "\n".join(chunks)


def render_embedded_bundle(parts: UiBundleParts) -> str:
    """Render a self-contained JavaScript bundle with embedded HTML/CSS/JS.

    Inputs:
      - parts: Extracted UI asset components.
    Outputs:
      - JavaScript bundle source text that mounts the UI on page load.
    """

    bootstrap_json = json.dumps(parts.bootstrap_script)
    app_json = json.dumps(parts.app_script)
    html_json = json.dumps(parts.body_markup)
    css_json = json.dumps(parts.styles_css)

    return f"""/* Generated by scripts/build_admin_ui_bundle.py (embedded mode). */
/* eslint-disable */
(function () {{
\t'use strict';
\tif (window.__FOGHORN_ADMIN_UI_BUNDLE_LOADED__) {{
\t\treturn;
\t}}
\twindow.__FOGHORN_ADMIN_UI_BUNDLE_LOADED__ = true;
\tvar BOOTSTRAP_JS = {bootstrap_json};
\tvar APP_JS = {app_json};
\tvar BODY_HTML = {html_json};
\tvar STYLES_CSS = {css_json};

\tfunction runScript(jsText) {{
\t\tif (!jsText) {{
\t\t\treturn;
\t\t}}
\t\t(new Function(jsText))();
\t}}

\tfunction ensureStyles() {{
\t\tvar existing = document.querySelector('style[data-foghorn-admin-ui-bundle]');
\t\tif (existing) {{
\t\t\treturn;
\t\t}}
\t\tvar styleEl = document.createElement('style');
\t\tstyleEl.setAttribute('data-foghorn-admin-ui-bundle', 'true');
\t\tstyleEl.textContent = STYLES_CSS;
\t\tdocument.head.appendChild(styleEl);
\t}}

\tfunction mountUi() {{
\t\tif (!document.body) {{
\t\t\treturn;
\t\t}}
\t\tdocument.body.innerHTML = BODY_HTML;
\t\tensureStyles();
\t\trunScript(BOOTSTRAP_JS);
\t\trunScript(APP_JS);
\t}}

\tif (document.readyState === 'loading') {{
\t\tdocument.addEventListener('DOMContentLoaded', mountUi, {{ once: true }});
\t}} else {{
\t\tmountUi();
\t}}
}})();
"""


def write_bundle(output_path: Path, bundle_js: str) -> None:
    """Write bundle text to disk, creating parent directories as needed.

    Inputs:
      - output_path: Destination path for the built bundle.
      - bundle_js: Rendered JavaScript bundle content.
    Outputs:
      - Writes file content to output_path.
    """

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(bundle_js, encoding="utf-8")


def main() -> int:
    """Run the bundle build flow.

    Inputs:
      - CLI args parsed via parse_args().
    Outputs:
      - Process exit code (0 on success, 1 on failure).
    """

    args = parse_args()
    index_path = Path(args.index)
    styles_path = Path(args.styles)
    output_path = Path(args.output)

    try:
        parts = extract_assets(index_path=index_path, styles_path=styles_path)
        if args.runtime_only:
            bundle_js = render_runtime_only_bundle(parts)
        else:
            bundle_js = render_embedded_bundle(parts)
        write_bundle(output_path=output_path, bundle_js=bundle_js)
    except Exception as exc:  # noqa: BLE001
        print(f"Failed to build admin UI bundle: {exc}")
        return 1

    mode = "runtime-only" if args.runtime_only else "embedded"
    print(f"Built {mode} admin UI bundle: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
