apiVersion: 1

datasources:
  - name: Foghorn InfluxDB
    uid: foghorn-influxdb
    type: influxdb
    access: proxy
    url: ${INFLUXDB_URL}
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
